markdown: rdiscount
pygments: true
exclude:
- Rakefile
- README.textile
- public
- Gemfile
- Gemfile.lock
- deploy.sh
flickr_set:
 api_key: '0b565d9778e50b0167262f730918a69c'
 shared_secret: '505be464f2fd0a1c'